In [1]:
import numpy as np

In [52]:
# Size
n = 100
d = 10

# Unknown
theta_star = np.random.normal(size=(d,1))
sigma = np.abs(np.random.normal())
eps = np.random.normal(scale=sigma, size=(n,1))


# Known
X = np.random.normal(size=(n, d))
Y = X.dot(theta_star) + eps

In [53]:
X

array([[ 6.82930562e-01,  8.13647744e-01,  3.11493282e-01,
         6.47149617e-01,  1.65274628e+00, -6.64838383e-01,
         1.56862147e+00, -3.10039725e-01,  1.20688139e-01,
         7.78269518e-01],
       [ 1.92343000e-01,  1.90712916e-01, -2.33698398e-01,
         2.46263015e-02,  4.25476459e-01,  3.65129736e-01,
         1.25737086e+00,  4.44841886e-01,  2.60935273e-01,
         3.87656839e-01],
       [-1.35701960e+00,  7.88445570e-01, -8.31388416e-02,
        -2.03475681e+00, -3.73662869e-01, -1.31983503e+00,
        -2.85433519e-01,  4.04150922e-01,  3.38463503e-01,
         9.98709276e-01],
       [-4.05752072e-01, -8.86843264e-01,  1.78315899e+00,
         3.51622020e-01,  1.14262198e+00,  7.17503638e-01,
        -1.38364516e+00, -9.41458077e-01,  1.11741127e+00,
        -1.80850948e+00],
       [ 1.35636174e-01, -2.04400857e-01, -8.47372183e-02,
        -7.81404050e-01, -1.33316799e+00, -2.80611361e-01,
         1.41821656e+00, -9.10534285e-01,  5.76773352e-01,
         2.

In [54]:
Y

array([[-0.95480452],
       [-0.19853739],
       [ 5.1682274 ],
       [-2.36887644],
       [ 0.95249906],
       [ 2.11350724],
       [ 0.47526294],
       [-3.89396214],
       [ 0.43464269],
       [ 3.69274508],
       [ 2.69765774],
       [-1.07283875],
       [-3.63837124],
       [ 0.04613955],
       [-3.16169387],
       [-1.21532373],
       [ 0.95969741],
       [-1.26611678],
       [ 1.33808709],
       [ 1.80293267],
       [-0.52941231],
       [ 1.28305572],
       [ 0.22241571],
       [-5.22978317],
       [ 5.08301973],
       [-0.48449507],
       [ 1.42544186],
       [-0.58886339],
       [ 2.12094314],
       [ 2.20042774],
       [ 3.6531448 ],
       [-0.49319298],
       [-1.11604035],
       [-0.38116052],
       [-0.48496863],
       [-3.50252581],
       [-5.27915133],
       [ 0.45684707],
       [ 6.40144513],
       [ 0.17194985],
       [-2.8395529 ],
       [-0.69533037],
       [-0.38310201],
       [ 4.12517452],
       [-1.32117408],
       [-0

In [55]:
XtX = X.transpose().dot(X)
XtX_inv = np.linalg.inv(XtX)
XtY = X.transpose().dot(Y)
theta_hat = XtX_inv.dot(XtY)

In [56]:
Y_pred = X.dot(theta_hat)

In [57]:
MSE = sum((Y_pred - Y) ** 2)
sigma2_hat = MSE / (n - d)

In [58]:
theta_star, theta_hat

(array([[-0.61701988],
        [-0.00961257],
        [-1.35160002],
        [-1.15224353],
        [ 0.71444028],
        [-0.39204773],
        [-0.88969811],
        [ 0.21288978],
        [ 0.65579978],
        [ 1.03825546]]),
 array([[-0.54687742],
        [-0.02964201],
        [-1.45345751],
        [-1.11186685],
        [ 0.72590502],
        [-0.43329522],
        [-0.90361339],
        [ 0.12780172],
        [ 0.62153068],
        [ 0.99645935]]))

In [59]:
sigma ** 2, sigma2_hat

(0.21864007062225724, array([0.20882116]))