## Exercice 1
### Calcule de f_star

* Si X=0, P[Y=1] = 1/4 < 1/2 < 3/4 = P[-1] --> f_star(0) = -1
* Si X=1, P[Y=1] = 2/5 < 1/2               --> f_star(1) = -1
* Si X=2, P[Y=1] = 1/3 < 1/2               --> f_star(2) = -1
* Si X=3, P[Y=1] = 3/4 > 1/2               --> f_star(3) = +1
* Si X=4, P[Y=1] = 5/6 > 1/2               --> f_star(4) = +1
* Si X=5, P[Y=1] = 7/8 > 1/2               --> f_star(5) = +1

### Calcule de l'erreur de Bayes

* Si X=0 --> min(1/4, 3/4) = 1/4
* Si X=1 --> min(2/5, 3/5) = 2/5
* Si X=2 --> min(1/3, 2/3) = 1/3
* Si X=3 --> min(3/4, 1/4) = 1/4
* Si X=4 --> min(5/6, 1/6) = 1/6
* Si X=5 --> min(7/8, 1/8) = 1/8

Donc l'erreur de bayes = 1/6 * (1/4 + 2/5 + 1/3 + 1/4 + 1/6 + 1/8)

In [14]:
## Exercice 2
import pandas as pd
import numpy as np

In [15]:
def generate_output_data(X):
    """
        generate input and output data (supervised learning)
        according to the linear model, fixed design setup
        - X is fixed
        - Y is random, according to

        Y = Xtheta_star + epsilon

        where epsilon is a centered gaussian noise vector with variance
        sigma*In

        Parameters:
            X (float matrix): (n, d) design matrix
            theta_star (float vector): (d, 1) vector (optimal parameter)
            sigma (float): variance each epsilon

        Returns:
            Y (float matrix): output vector (n, 1)
    """

    # output data
    n = X.shape[0]
    #d = 1
    Y = []
    for i in range(n):
        if X[i] == 0:
            Y.append(2 * np.random.binomial(1, 1 / 4) - 1)
        if X[i] == 1:
            Y.append(2 * np.random.binomial(1, 2 / 5) - 1)
        if X[i] == 2:
            Y.append(2 * np.random.binomial(1, 1 / 3) - 1)
        if X[i] == 3:
            Y.append(2 * np.random.binomial(1, 3 / 4) - 1)
        if X[i] == 4:
            Y.append(2 * np.random.binomial(1, 5 / 6) - 1)
        if X[i] == 5:
            Y.append(2 * np.random.binomial(1, 7 / 8) - 1)
    return np.array(Y)[:,None]

In [16]:
n = 20
#d = 1

X = np.random.randint(0, 6, (n, 1))
Y = generate_output_data(X)

In [17]:
X

array([[3],
       [4],
       [0],
       [4],
       [5],
       [0],
       [2],
       [1],
       [4],
       [3],
       [3],
       [0],
       [1],
       [1],
       [5],
       [1],
       [2],
       [5],
       [3],
       [5]])

In [18]:
Y

array([[ 1],
       [ 1],
       [-1],
       [ 1],
       [-1],
       [-1],
       [-1],
       [-1],
       [ 1],
       [-1],
       [ 1],
       [-1],
       [ 1],
       [ 1],
       [-1],
       [ 1],
       [-1],
       [ 1],
       [ 1],
       [ 1]])

In [19]:
mode = []
for i in range(6):
    mode.append(pd.Series(Y[X == i]).value_counts().index[0])

def f_tilda(X):
    Y_pred = []
    for x in X:
        Y_pred.append(mode[int(x)])
    return np.array(Y_pred)[:, None]

mode

[-1, 1, -1, 1, 1, -1]

In [20]:
Y_pred = f_tilda(X)
Y_pred

array([[ 1],
       [ 1],
       [-1],
       [ 1],
       [-1],
       [-1],
       [-1],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [-1],
       [ 1],
       [ 1],
       [-1],
       [ 1],
       [-1],
       [-1],
       [ 1],
       [-1]])

In [21]:
empirical_risk_tilda = (Y != Y_pred).mean() # Empirical and f_tilda

In [22]:
empirical_risk_tilda

0.2

In [23]:
bayes_risk = 1/6 * (1/4 + 2/5 + 1/3 + 1/4 + 1/6 + 1/8) ## For exact f_star

In [24]:
bayes_risk

0.25416666666666665

In [25]:
## BONUS

def f_star(X):
    Y_pred = []
    for x in X:
        if x < 3:
            Y_pred.append(-1)
        else:
            Y_pred.append(1)
    return np.array(Y_pred)[:, None]

Y_star_pred = f_star(X)

empirical_risk_star = (Y != Y_star_pred).mean() # Empirical and f_tilda

In [26]:
empirical_risk_star

0.3