In [19]:
import numpy as np

In [20]:
# Size
n = 100000000
d = 4

# Unknown
theta_star = np.random.normal(size=(d,1))
sigma = np.abs(np.random.normal())
eps = np.random.normal(scale=sigma, size=(n,1))


# Known
X = np.random.normal(size=(n, d))
Y = X.dot(theta_star) + eps

In [21]:
X

array([[ 1.00759393, -0.23525412, -0.07331628, -0.34567668],
       [-0.21717894, -0.23318982,  0.62212253, -0.24064679],
       [-2.09943619, -0.95580568,  0.41629567,  1.74926249],
       ...,
       [-0.84894681, -1.34336031, -0.29996994,  0.69657615],
       [-0.19688106, -0.07321007, -0.08737678, -0.27114597],
       [-0.92560467,  1.06808765,  0.10676935,  0.84446419]])

In [22]:
Y

array([[ 1.07849662],
       [ 2.98454287],
       [-0.14715035],
       ...,
       [-0.39649363],
       [-1.86868479],
       [-2.00878855]])

In [23]:
XtX = X.transpose().dot(X)
XtX_inv = np.linalg.inv(XtX)
XtY = X.transpose().dot(Y)
theta_hat = XtX_inv.dot(XtY)

In [24]:
Y_pred = X.dot(theta_hat)

In [25]:
MSE = sum((Y_pred - Y) ** 2)
sigma2_hat = MSE / (n - d)

In [26]:
theta_star, theta_hat

(array([[-0.02823178],
        [ 0.50259961],
        [ 0.90747298],
        [-0.32085864]]),
 array([[-0.02821451],
        [ 0.50245243],
        [ 0.90731736],
        [-0.32086149]]))

In [27]:
sigma ** 2, sigma2_hat

(1.4443209292402932, array([1.44437757]))